package net.dublinux.ignition.traefik;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;

import net.dublinux.ignition.config.IgnitionProperties;
import net.dublinux.ignition.zone.Zone;
import net.dublinux.ignition.zone.ZoneRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

/**
 * Writes the Traefik file-provider snippets under {@code <work>/control/dynamic/}:
 * {@code _platform.yml} routes {@code admin.<BASE_DOMAIN>} and {@code <slug>.yml}
 * routes {@code admin.<slug>.<BASE_DOMAIN>} — both to this control plane, the
 * latter carrying its own {@code *.<slug>.<BASE_DOMAIN>} cert request.
 *
 * <p>The work dir is ephemeral, so on startup the whole directory is rebuilt
 * from the {@code zone} rows.
 */
@Component
public class TraefikDynamicConfig {

    private static final Logger log = LoggerFactory.getLogger(TraefikDynamicConfig.class);

    private final IgnitionProperties props;
    private final ZoneRepository zones;

    /**
     * Where Traefik reaches this service — {@code http://ignition-control:8790}
     * once it ships as a container on {@code traefik-public}.
     */
    @Value("${ignition.control-plane-url:http://host.docker.internal:8790}")
    private String controlPlaneUrl;

    public TraefikDynamicConfig(IgnitionProperties props, ZoneRepository zones) {
        this.props = props;
        this.zones = zones;
    }

    /** Rebuild the full dynamic directory from the DB as soon as the service is up. */
    @EventListener(ApplicationReadyEvent.class)
    public void rebuild() {
        writePlatformRouter();
        for (Zone z : zones.findAll()) {
            writeZoneRouter(z);
        }
        log.info("rebuilt Traefik dynamic config for {} zone(s)", zones.findAll().size());
    }

    public void writePlatformRouter() {
        write("_platform.yml", """
                # generated by ignition-control — routes admin.%1$s to the control plane
                http:
                  routers:
                    ign-platform:
                      rule: "Host(`admin.%1$s`)"
                      entryPoints: ["websecure"]
                      service: ign-control
                      tls: {certResolver: le}
                  services:
                    ign-control:
                      loadBalancer:
                        servers:
                          - url: "%2$s"
                """.formatted(props.getBaseDomain(), controlPlaneUrl));
    }

    public void writeZoneRouter(Zone zone) {
        String slug = zone.slug();
        String base = props.getBaseDomain();
        // PRIVATE zones gain a forwardAuth middleware on git.<slug> / *.apps.<slug>
        // in AUTH-DESIGN step 7; the admin.<slug> router below is always members-only.
        write(slug + ".yml", """
                # generated by ignition-control — routes admin.%1$s.%2$s to the control plane
                http:
                  routers:
                    ign-zone-%1$s:
                      rule: "Host(`admin.%1$s.%2$s`)"
                      entryPoints: ["websecure"]
                      service: ign-control
                      tls:
                        certResolver: le
                        domains:
                          - main: "%1$s.%2$s"
                            sans: ["*.%1$s.%2$s"]
                """.formatted(slug, base));
    }

    public void removeZoneRouter(String slug) {
        try {
            Files.deleteIfExists(props.controlDynamicDir().resolve(slug + ".yml"));
        } catch (IOException e) {
            throw new UncheckedIOException("removing router for " + slug, e);
        }
    }

    private void write(String name, String content) {
        Path dir = props.controlDynamicDir();
        try {
            Files.createDirectories(dir);
            Files.writeString(dir.resolve(name), content);
        } catch (IOException e) {
            throw new UncheckedIOException("writing " + dir.resolve(name), e);
        }
    }
}
