package net.dublinux.ignition.traefik;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import net.dublinux.ignition.config.IgnitionProperties;
import net.dublinux.ignition.zone.Zone;
import net.dublinux.ignition.zone.ZoneRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

/**
 * Writes the Traefik file-provider snippet under {@code <work>/control/dynamic/}:
 * {@code _platform.yml} routes the bare {@code <BASE_DOMAIN>} apex to this
 * control plane — the one console, for every role. (There used to also be a
 * per-zone {@code admin.<slug>.<BASE_DOMAIN>} router to the same backend;
 * dropped — a hostname was never what gated who could do what, the session's
 * role always was, so it added an ACME cert request per zone for nothing. A
 * team's console is {@code /teams/<slug>} on this same host now.
 * {@link #removeZoneRouter} stays, to clean up any {@code <slug>.yml} a
 * pre-existing deployment still has lying around.)
 *
 * <p>The work dir is ephemeral, so on startup the file is rewritten from the
 * {@code IgnitionProperties} config, not per-zone state.
 */
@Component
public class TraefikDynamicConfig {

    private static final Logger log = LoggerFactory.getLogger(TraefikDynamicConfig.class);

    private final IgnitionProperties props;
    private final ZoneRepository zones;

    /**
     * Where Traefik reaches this service — {@code http://ignition-control:8790}
     * once it ships as a container on {@code traefik-public}.
     */
    @Value("${ignition.control-plane-url:http://host.docker.internal:8790}")
    private String controlPlaneUrl;

    public TraefikDynamicConfig(IgnitionProperties props, ZoneRepository zones) {
        this.props = props;
        this.zones = zones;
    }

    /** Rebuild the dynamic directory as soon as the service is up. */
    @EventListener(ApplicationReadyEvent.class)
    public void rebuild() {
        try {
            writePlatformRouter();
            log.info("rebuilt Traefik dynamic config");
        } catch (RuntimeException e) {
            log.error("could not rebuild Traefik dynamic config on startup", e);
        }
    }

    public void writePlatformRouter() {
        write("_platform.yml", """
                # generated by ignition-control — routes %1$s to the control plane
                http:
                  routers:
                    ign-platform:
                      rule: "Host(`%1$s`)"
                      entryPoints: ["websecure"]
                      service: ign-control
                      tls: {certResolver: le}
                  services:
                    ign-control:
                      loadBalancer:
                        servers:
                          - url: "%2$s"
                """.formatted(props.getBaseDomain(), controlPlaneUrl));
    }

    public void removeZoneRouter(String slug) {
        try {
            Files.deleteIfExists(props.controlDynamicDir().resolve(slug + ".yml"));
        } catch (IOException e) {
            throw new UncheckedIOException("removing router for " + slug, e);
        }
    }

    private void write(String name, String content) {
        Path dir = props.controlDynamicDir();
        try {
            Files.createDirectories(dir);
            Files.writeString(dir.resolve(name), content);
        } catch (IOException e) {
            throw new UncheckedIOException("writing " + dir.resolve(name), e);
        }
    }
}
