package net.dublinux.ignition.traefik;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;

import net.dublinux.ignition.config.IgnitionProperties;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

/**
 * Writes the Traefik file-provider snippets under
 * {@code state/control/dynamic/}: {@code _platform.yml} routes
 * {@code admin.<BASE_DOMAIN>} and {@code <slug>.yml} routes
 * {@code admin.<slug>.<BASE_DOMAIN>} — both to this control plane, the latter
 * carrying its own {@code *.<slug>.<BASE_DOMAIN>} cert request. Mirrors the
 * heredocs in {@code provision-zone.sh}.
 */
@Component
public class TraefikDynamicConfig {

    private final IgnitionProperties props;

    /**
     * Where Traefik reaches this service. {@code host.docker.internal:<port>}
     * while ign-control runs bare on the control host; becomes
     * {@code http://ignition-control:8790} once it ships as a container on
     * {@code traefik-public}.
     */
    @Value("${ignition.control-plane-url:http://host.docker.internal:8790}")
    private String controlPlaneUrl;

    public TraefikDynamicConfig(IgnitionProperties props) {
        this.props = props;
    }

    /** Ensure the platform router exists as soon as the service is up. */
    @EventListener(ApplicationReadyEvent.class)
    public void onStartup() {
        writePlatformRouter();
    }

    public void writePlatformRouter() {
        write("_platform.yml", """
                # generated by ignition-control — routes admin.%1$s to the control plane
                http:
                  routers:
                    ign-platform:
                      rule: "Host(`admin.%1$s`)"
                      entryPoints: ["websecure"]
                      service: ign-control
                      tls: {certResolver: le}
                  services:
                    ign-control:
                      loadBalancer:
                        servers:
                          - url: "%2$s"
                """.formatted(props.getBaseDomain(), controlPlaneUrl));
    }

    public void writeZoneRouter(String slug) {
        String base = props.getBaseDomain();
        write(slug + ".yml", """
                # generated by ignition-control — routes admin.%1$s.%2$s to the control plane
                http:
                  routers:
                    ign-zone-%1$s:
                      rule: "Host(`admin.%1$s.%2$s`)"
                      entryPoints: ["websecure"]
                      service: ign-control
                      tls:
                        certResolver: le
                        domains:
                          - main: "%1$s.%2$s"
                            sans: ["*.%1$s.%2$s"]
                """.formatted(slug, base));
    }

    public void removeZoneRouter(String slug) {
        try {
            Files.deleteIfExists(props.controlDynamicDir().resolve(slug + ".yml"));
        } catch (IOException e) {
            throw new UncheckedIOException("removing router for " + slug, e);
        }
    }

    private void write(String name, String content) {
        Path dir = props.controlDynamicDir();
        try {
            Files.createDirectories(dir);
            Files.writeString(dir.resolve(name), content);
        } catch (IOException e) {
            throw new UncheckedIOException("writing " + dir.resolve(name), e);
        }
    }
}
