#!/usr/bin/env bash
# Stand up one team's full stack: Forgejo + private DinD + Actions runner, and
# register a deploy token so the team's CI can push a live app.
#
#   BASE_DOMAIN=hz.example.com ./scripts/provision-team.sh <slug> [index]
#
# <index> is a stable roster ordinal recorded in state/<slug>/team.env; it no
# longer maps to a port now that Traefik routes Forgejo by hostname.
#
# Idempotent: re-running with the same slug re-renders and re-applies.
set -euo pipefail
cd "$(dirname "$0")/.."
. scripts/lib.sh

# --- per-team resource quotas (override via env) ------------------------------
: "${CPU_FORGEJO:=1.0}" "${MEM_FORGEJO:=1g}"
: "${CPU_DIND:=2.0}"    "${MEM_DIND:=4g}"
: "${CPU_RUNNER:=1.0}"  "${MEM_RUNNER:=2g}"
: "${CPU_APP:=1.0}"     "${MEM_APP:=1g}"
: "${APP_PORT:=8080}"        # the port the team's app is expected to listen on
: "${RUNNER_CAPACITY:=4}"

need docker; need envsubst; need openssl; need od
[ $# -ge 1 ] || die "usage: $0 <slug> [index]"
SLUG="$1"; INDEX="${2:-0}"
valid_slug "$SLUG" || die "slug must be [a-z0-9-], <=40 chars, no leading/trailing dash"
[ "$INDEX" -ge 0 ] 2>/dev/null || die "index must be a non-negative integer"
: "${BASE_DOMAIN:?set BASE_DOMAIN (e.g. hz.example.com)}"

export TEAM_SLUG="$SLUG"
export BASE_DOMAIN CPU_FORGEJO MEM_FORGEJO CPU_DIND MEM_DIND CPU_RUNNER MEM_RUNNER

GIT_HOST="git.$SLUG.$BASE_DOMAIN"
S="$STATE_DIR/$SLUG"
mkdir -p "$S"
echo "==> team=$SLUG  forgejo=https://$GIT_HOST/  app=https://$SLUG.$BASE_DOMAIN/"

render "$TEMPLATES/docker-compose.team.yml.tmpl" "$TEAM_TMPL_VARS" "$S/docker-compose.yml"
# The runner service bind-mounts ./runner-config.yml; give compose a placeholder
# so `up -d forgejo dind` doesn't choke on a missing bind source.
[ -f "$S/runner-config.yml" ] || echo "# generated by provision-team.sh" > "$S/runner-config.yml"

# --- phase 1: forgejo + dind ------------------------------------------------
dc "$SLUG" up -d forgejo dind

printf '    waiting for forgejo'
for _ in $(seq 1 60); do
    state=$(dc "$SLUG" ps --format '{{.Service}} {{.Health}}' | awk '$1=="forgejo"{print $2}')
    [ "$state" = "healthy" ] && { echo " ok"; break; }
    printf '.'; sleep 2
done
[ "${state:-}" = "healthy" ] || die "forgejo did not become healthy"

# --- runner registration: shared secret (two-phase: forgejo must exist) ----
if [ ! -s "$S/runner-secret" ]; then
    openssl rand -hex 20 > "$S/runner-secret"        # 40 hex chars, Forgejo's required length
fi
SECRET="$(cat "$S/runner-secret")"
UUID="$(forgejo_uuid "$SECRET")"

# Idempotent-ish: registering the same secret again is harmless.
dc "$SLUG" exec -T -u git forgejo \
    forgejo forgejo-cli actions register --keep-labels --name "team-$SLUG" --secret "$SECRET" >/dev/null

# --- generate the runner config (computed values -> not a template) --------
cat > "$S/runner-config.yml" <<EOF
log:
  level: info
runner:
  file: /data/.runner
  capacity: ${RUNNER_CAPACITY}
  timeout: 3h
  labels:
    - "ubuntu-latest:docker://code.forgejo.org/oci/node:22-bookworm"
    - "docker-cli:docker://code.forgejo.org/oci/docker:cli"
container:
  network: host
  valid_volumes: []
server:
  connections:
    default:
      url: http://forgejo:3000
      uuid: ${UUID}
      token: ${SECRET}
EOF

# --- phase 2: bring up the runner (bind-mounts the config we just wrote) ---
dc "$SLUG" up -d
dc "$SLUG" restart runner   # re-read the config if it was already running

# --- deploy token: CI -> deploy-agent bearer -----------------------------
[ -s "$S/deploy-token" ] || openssl rand -hex 32 > "$S/deploy-token"

cat > "$S/team.env" <<EOF
TEAM_SLUG=$SLUG
TEAM_INDEX=$INDEX
BASE_DOMAIN=$BASE_DOMAIN
APP_PORT=$APP_PORT
GIT_HOST=$GIT_HOST
REGISTRY=$GIT_HOST
FORGEJO_URL=https://$GIT_HOST/
APP_URL=https://$SLUG.$BASE_DOMAIN/
EOF
date +%s > "$S/last-activity"

cat <<EOF

  provisioned: $SLUG
    Forgejo          https://$GIT_HOST/
    Live app (once deployed)  https://$SLUG.$BASE_DOMAIN/
    Registry         $GIT_HOST
    Deploy token     $S/deploy-token   (give to CI as DEPLOY_TOKEN secret)
    Runner secret    $S/runner-secret

  DNS: git.$SLUG.$BASE_DOMAIN must resolve to this host (a *.$SLUG.$BASE_DOMAIN
  record, or add it per team — see CLAUDE.md).

  Next: create an admin user in the Forgejo UI, seed the starter repo with
  examples/deploy.yml, and set repo vars/secrets (REGISTRY, DEPLOY_URL,
  FORGEJO_TOKEN, DEPLOY_TOKEN). See CLAUDE.md next tasks.
EOF
