#!/usr/bin/env bash
# gen-templates.sh — write the demo's config templates (with <PLACEHOLDER>s)
# and a demo.conf.example listing every value you need to supply.
#
# Then:  edit demo.conf  →  ./render.sh demo.conf  →  files land in ./out/
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
tpl="$here/templates"
mkdir -p "$tpl"

# ---------------------------------------------------------------- demo.conf.example
cat > "$here/demo.conf.example" <<'EOF'
# demo.conf — one file, all the values. Copy to demo.conf and fill in.
# Format: KEY=value, one per line. The value is everything after the first '='
# (taken literally; only trailing whitespace is trimmed). Comments are whole
# lines starting with '#' — never inline. Blank values for the secrets and the
# WireGuard keys are generated by render.sh.

# --- addresses ---
# hetzner's existing public IPv4
PUBLIC_IP=

# --- domain / ACME (DNS-01) ---
BASE_DOMAIN=ignition.classesarecode.net
# Let's Encrypt account contact (any mailbox you read)
ACME_EMAIL=
# one of: joker | desec | cloudflare
ACME_DNS_PROVIDER=joker

# fill ONLY the lines matching ACME_DNS_PROVIDER:
#   joker  -> Joker "Dynamic DNS" username/password (uses JOKER_API_MODE=SVC)
JOKER_USERNAME=
JOKER_PASSWORD=
#   desec  -> deSEC.io API token
DESEC_TOKEN=
#   cloudflare -> scoped API token
CF_DNS_API_TOKEN=

# --- SMTP (ignition-control refuses to start without it) ---
IGN_SMTP_HOST=
IGN_SMTP_PORT=587
IGN_SMTP_USERNAME=
IGN_SMTP_PASSWORD=
IGN_SMTP_FROM=Ignition <ignition@classesarecode.net>

# --- secrets (blank = auto-generate) ---
IGN_SECRET_KEY=
IGN_USER_SECRET_PEPPER=
POSTGRES_PASSWORD=

# --- WireGuard (blank keys = auto-generate with `wg`) ---
WG_PORT=51820
WG_HETZNER_IP=10.44.0.1
WG_SPITFIRE_IP=10.44.0.11
WG_SUBNET=10.44.0.0/24
HETZNER_WG_PRIVKEY=
HETZNER_WG_PUBKEY=
SPITFIRE_WG_PRIVKEY=
SPITFIRE_WG_PUBKEY=
EOF

# ---------------------------------------------------------------- part 1: spitfire
cat > "$tpl/ignition.env" <<'EOF'
# Rendered env for the demo. Copy to the repo root as  ignition/.env  —
# `docker compose` auto-loads it. Compose's parser takes each value literally
# (no shell), so spaces and </>/= in the values are fine.
BASE_DOMAIN=<BASE_DOMAIN>
ACME_EMAIL=<ACME_EMAIL>
ACME_DNS_PROVIDER=<ACME_DNS_PROVIDER>

IGN_SECRET_KEY=<IGN_SECRET_KEY>
IGN_USER_SECRET_PEPPER=<IGN_USER_SECRET_PEPPER>
POSTGRES_PASSWORD=<POSTGRES_PASSWORD>
IGN_PUBLIC_URL=https://<BASE_DOMAIN>

IGN_SMTP_HOST=<IGN_SMTP_HOST>
IGN_SMTP_PORT=<IGN_SMTP_PORT>
IGN_SMTP_USERNAME=<IGN_SMTP_USERNAME>
IGN_SMTP_PASSWORD=<IGN_SMTP_PASSWORD>
IGN_SMTP_FROM=<IGN_SMTP_FROM>
EOF

cat > "$tpl/acme.env" <<'EOF'
# acme.env — DNS-01 provider credentials for Traefik (part 1). chmod 600.
<ACME_ENV_BODY>
EOF

# ---------------------------------------------------------------- part 2: wireguard
cat > "$tpl/hetzner-wg0.conf" <<'EOF'
# hetzner:/etc/wireguard/wg0.conf   (chmod 600)
[Interface]
Address    = <WG_HETZNER_IP>/24
ListenPort = <WG_PORT>
PrivateKey = <HETZNER_WG_PRIVKEY>

[Peer]   # spitfire
PublicKey  = <SPITFIRE_WG_PUBKEY>
AllowedIPs = <WG_SPITFIRE_IP>/32
EOF

cat > "$tpl/spitfire-wg0.conf" <<'EOF'
# spitfire:/etc/wireguard/wg0.conf   (chmod 600)
[Interface]
Address    = <WG_SPITFIRE_IP>/24
PrivateKey = <SPITFIRE_WG_PRIVKEY>

[Peer]   # hetzner
PublicKey           = <HETZNER_WG_PUBKEY>
Endpoint            = <PUBLIC_IP>:<WG_PORT>
AllowedIPs          = <WG_SUBNET>
PersistentKeepalive = 25
EOF

# ---------------------------------------------------------------- part 2: nginx
cat > "$tpl/hetzner-nginx-stream.conf" <<'EOF'
# hetzner:/etc/nginx/stream-ignition.conf
# Add this line to /etc/nginx/nginx.conf at the TOP LEVEL (sibling of `http {}`):
#     include /etc/nginx/stream-ignition.conf;
# and move Apache off the public :443 :  ports.conf  Listen 443 -> Listen 127.0.0.1:443

stream {
    # route by TLS SNI without terminating TLS:
    #   demo names       -> spitfire over WireGuard
    #   every other host -> local Apache
    map $ssl_preread_server_name $ignition_backend {
        <BASE_DOMAIN>         <WG_SPITFIRE_IP>:443;   # the bare apex itself
        ~\.<BASE_DOMAIN_RE>$  <WG_SPITFIRE_IP>:443;    # every subdomain
        default               127.0.0.1:443;
    }

    server {
        listen        <PUBLIC_IP>:443;
        proxy_pass    $ignition_backend;
        ssl_preread   on;
        proxy_timeout 10m;                             # long-poll consoles, docker pushes
    }
}
EOF

echo "wrote:"
echo "  $here/demo.conf.example"
find "$tpl" -type f | sort | sed "s|^|  |"
echo
echo "next:  cp demo.conf.example demo.conf  &&  \$EDITOR demo.conf  &&  ./render.sh demo.conf"
